### ISSUE TITLE
Python API doesn't work

### ISSUE THREAD

**Issue by fhbzc** [woc-hack/tutorial#21] opened 2022-02-03 15:30 UTC
Hi:
    I'm trying to use oscar.py and access data with Python. I have done "git pull" before use.

In server da4, with the latest version of oscar, if run 
   
     import oscar

with Python3, it will report error
![image](https://user-images.githubusercontent.com/39660755/152372855-f733a3d0-4ece-436d-9e81-15ede50c34d2.png)

if run (as shown in the tutorial)

     from oscar import Author
     Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas

with Python2, it will report error
![image](https://user-images.githubusercontent.com/39660755/152373390-bf28d556-5b26-4ad2-a29e-2a1de972b29a.png)

other commands in tutorial also doesn't work. For example, run

       from oscar import Project
       Project('notcake_gcad').url

with Python2 will report
![image](https://user-images.githubusercontent.com/39660755/152373630-7a71e286-a796-4ca8-9da8-9bc4bc3fad54.png)

Please let me know how could I fix the problem. Thank you!

**Comment by audrism** [comment] 2022-02-03 16:44
Version U has placed databases in different locations, I'll try to make python api recognize them

**Comment by audrism** [comment] 2022-02-03 18:15
Not sure if it completely solves the problem, but I pushed an update

**Comment by sivanahamer** [comment] 2022-02-03 18:27
Hello,

The same error respective error continues to appear in both python versions after the latest update.

**Comment by audrism** [comment] 2022-02-03 18:46
You may need to build/and install it as per readme

Right now the focus is on python3 as py2 support probably should be dropped

**Comment by sivanahamer** [comment] 2022-02-03 19:16
Building and installing it (as per the installation instructions in Oscar.py) did fix the previous run time error!

Now, while running the following code with python3 in `da4`:
```
 Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commit_shas
```
It produces the following output:

```
(b'\x17\xab\xdb\xdc\x90\x19P\x16D*j\x8d\xd8\xe3\x8d\xea\x82R\x92\xae', b'\x9c\xdc\x91\x8b\xfb\xa1\x01\r\xe1]\x0c\x96\x8a\xf8\xee7\xc9\xc3\x00\xff', b'\xd9\xfch\ni\x19\x83\x00\xd3K\xc7\xe3\x1b\xba\xfe6\xe7\x18\\v')
```
There does seem to be an issue with the encoded information.

**Comment by audrism** [comment] 2022-02-03 20:37
These look like correct commits:
echo '"Albert Krawczyk" <pro-logic@optusnet.com.au>'| ~/lookup/getValues a2c
"Albert Krawczyk" <pro-logic@optusnet.com.au>;17abdbdc90195016442a6a8dd8e38dea825292ae;9cdc918bfba1010de15d0c968af8ee37c9c300ff;d9fc680a69198300d34bc7e31bbafe36e7185c76

I am not using python interface myself, so I do not know if this call should return binary (as is) or hex representation? To get hex you may want to use
```
for i in oscar.Author('"Albert Krawczyk" <pro-logic@optusnet.com.au>').commits: print (i)
... 
17abdbdc90195016442a6a8dd8e38dea825292ae
9cdc918bfba1010de15d0c968af8ee37c9c300ff
d9fc680a69198300d34bc7e31bbafe36e7185c76
```

If I look at the code, binaries seem to be the intended behavior:

``` 
    @cached_property
    def commit_shas(self):
        """ SHAs of Commits in which this blob have been
        introduced or modified.

        **NOTE: commits removing this blob are not included**
        """
        return slice20(self.read_tch('blob_commits'))
```

**Comment by sivanahamer** [comment] 2022-02-03 20:43
Perfect! Thank you so much for all the help :)

**Comment by audrism** [comment] 2022-02-15 17:30
I am closing the issue if there no more comments

**Closed by audrism** 2022-02-15 17:30 UTC
